# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('targets', '0001_initial'),
        ('sadmin', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='scansmodel',
#            name='plugin',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='sadmin.PluginsModel'),
#        ),
#        migrations.AddField(
#            model_name='scansmodel',
#            name='task',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='targets.TasksModel'),
#        ),
#        migrations.AddField(
#            model_name='hostvulnerabilitymodel',
#            name='host',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='agents.HostsModel'),
#        ),
#        migrations.AddField(
#            model_name='hostvulnerabilitymodel',
#            name='plugin',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='sadmin.PluginsModel'),
#        ),
#        migrations.AddField(
#            model_name='hostvulnerabilitymodel',
#            name='target',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='targets.TargetsModel'),
#        ),
#        migrations.AddField(
#            model_name='hostvulnerabilitymodel',
#            name='task',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='targets.TasksModel'),
#        ),
#        migrations.AddField(
#            model_name='hostvulnerabilitymodel',
#            name='vulnerability',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='sadmin.VulnerabilityModel'),
#        ),
#        migrations.AddField(
#            model_name='hostsmodel',
#            name='task',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='targets.TasksModel'),
#        ),
#        migrations.AddField(
#            model_name='hostservicesmodel',
#            name='host',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agents.HostsModel'),
#        ),
        migrations.AlterUniqueTogether(
            name='googlehackingkeywordmodels',
            unique_together=set([('category', 'keyword')]),
        ),
#        migrations.AddField(
#            model_name='crawldatamodel',
#            name='website',
#            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to='agents.HostsModel'),
#        ),
#        migrations.AlterUniqueTogether(
#            name='websitetechnologiesmodel',
#            unique_together=set([('website', 'technology')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='websitesubdomainsmodel',
#            unique_together=set([('subdomain', 'website')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='websitephishingdomaindetectmodel',
#            unique_together=set([('website', 'domain')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='websitemonitorcontentmodel',
#            unique_together=set([('old_content', 'new_content')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='websitegooglehackingdetectmodel',
#            unique_together=set([('website', 'keyword')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='websiteblacklistcheckingmodel',
#            unique_together=set([('website', 'type')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='serverconfigurationsmodel',
#            unique_together=set([('website', 'description')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='scansmodel',
#            unique_together=set([('task', 'plugin')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='hostvulnerabilitymodel',
#            unique_together=set([('host', 'scanner_scan_id', 'scanner_vuln_id')]),
#        ),
#       migrations.AlterUniqueTogether(
#            name='hostsmodel',
#            unique_together=set([('task', 'ip_addr')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='hostservicesmodel',
#            unique_together=set([('port', 'host')]),
#        ),
#        migrations.AlterUniqueTogether(
#            name='crawldatamodel',
#            unique_together=set([('website', 'path')]),
#        ),
    ]
