# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 02:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20180322_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansmodel',
            name='scripted_scan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=[], size=None),
        ),
    ]
