# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-02 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_auto_20180529_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityeventsmodels',
            unique_together=set([('type', 'alert', 'severity')]),
        ),
    ]
