# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20180603_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesecurityalertmodel',
            name='description',
            field=models.TextField(blank=True, choices=[('NEW_DEVICE', 'Detect new device in your network.'), ('DEVICE_TURN_OFF', 'A device is turn off in your network.'), ('DEVICE_CHANGE_IP', 'Ip address of device is changed.'), ('CANNOT_CONNECT_TO_TARGET', 'Cannot connect to target scan.'), ('NEW_SERVICE', 'New service is open on your device.'), ('SERVICE_CHANGED', 'A service is change information.'), ('SERVICE_CLOSED', 'A service is closed on your device.'), ('SERVICE_VERSION_TOO_OLD', 'The version of service is too old.'), ('NEW_VULNERABILITY', ''), ('VULNERABILITY_IS_NOT_FIX', ''), ('NEW_SESSION', 'Penetration testing is successful. A new session is created.'), ('BKACLIST_DETECTED', 'Your domain is making blacklist by domain blacklists checker.'), ('MALWARE_DETECTED', 'A malware is detect in website link.'), ('WEBSITE_CONTENT_DETECTED', 'Website content is changed.'), ('SERVER_STATUS', 'server status'), ('SERVICE_STATUS', 'services status')], null=True),
        ),
        migrations.AlterField(
            model_name='websitesecurityalertmodel',
            name='solution',
            field=models.TextField(blank=True, choices=[('NEW_DEVICE', 'Please check list devices connected in your network.'), ('DEVICE_TURN_OFF', 'Please check your network connection with your device.'), ('DEVICE_CHANGE_IP', "Please check network connection if you don't setting dhcp."), ('CANNOT_CONNECT_TO_TARGET', 'Please check your network connection of your device and your targets.'), ('NEW_SERVICE', "Please check the service of your device is you don't open port."), ('SERVICE_CHANGED', "Please check the service of your device is you don't do this."), ('SERVICE_CLOSED', "Please check the service of your device is you don't close port."), ('SERVICE_VERSION_TOO_OLD', 'Please update the last version of software.'), ('NEW_VULNERABILITY', ''), ('VULNERABILITY_IS_NOT_FIX', ''), ('NEW_SESSION', ''), ('BKACLIST_DETECTED', 'Please check mail or website content or contact domain blacklists checker with to unblock.'), ('MALWARE_DETECTED', 'Please check website content source security.'), ('WEBSITE_CONTENT_DETECTED', ''), ('SERVER_STATUS', 'server status'), ('SERVICE_STATUS', 'services status')], null=True),
        ),
    ]
