# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_auto_20180603_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityeventsmodels',
            name='alert',
            field=models.CharField(choices=[('NEW_DEVICE', 'New device detected'), ('DEVICE_TURN_OFF', 'Device is turn off'), ('DEVICE_CHANGE_IP', 'Device is changed ip'), ('CANNOT_CONNECT_TO_TARGET', 'Cannot connect to target scan.'), ('NEW_SERVICE', 'New service detected'), ('SERVICE_CHANGED', 'Service is changed'), ('SERVICE_CLOSED', 'Service is closed'), ('SERVICE_VERSION_TOO_OLD', 'Service verion is too old'), ('NEW_VULNERABILITY', 'New vulnerability'), ('VULNERABILITY_IS_NOT_FIX', 'Vulnerability is not fix'), ('NEW_SESSION', 'New session'), ('NEW_PENETRATION', 'New penetration testing attact is successful.'), ('BKACLIST_DETECTED', 'Blackist detected'), ('MALWARE_DETECTED', 'Malware is detected'), ('WEBSITE_CONTENT_DETECTED', 'Website content is change detected'), ('SERVER_STATUS', 'Server status'), ('SERVICE_STATUS', 'Services status')], default='NEW_DEVICE', max_length=50),
        ),
        migrations.AlterField(
            model_name='securityeventsmodels',
            name='type',
            field=models.CharField(choices=[('HOST', 'host'), ('SERVICE', 'service'), ('VULNERABLITY', 'vulnerablity'), ('PENETRATION', 'Penetration'), ('BLACKLIST', 'blacklist'), ('MALWARE', 'malware'), ('MONITOR', 'realtime monitor')], default='IP ADDRESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='websitesecurityalertmodel',
            name='description',
            field=models.TextField(blank=True, choices=[('NEW_DEVICE', 'Detect new device in your network.'), ('DEVICE_TURN_OFF', 'A device is turn off in your network.'), ('DEVICE_CHANGE_IP', 'Ip address of device is changed.'), ('CANNOT_CONNECT_TO_TARGET', 'Cannot connect to target scan.'), ('NEW_SERVICE', 'New service is open on your device.'), ('SERVICE_CHANGED', 'A service is change information.'), ('SERVICE_CLOSED', 'A service is closed on your device.'), ('SERVICE_VERSION_TOO_OLD', 'The version of service is too old.'), ('NEW_VULNERABILITY', ''), ('VULNERABILITY_IS_NOT_FIX', ''), ('NEW_SESSION', 'Penetration testing is successful. A new session is created.'), ('NEW_PENETRATION', 'New penetration testing attact is successful.'), ('BKACLIST_DETECTED', 'Your domain is making blacklist by domain blacklists checker.'), ('MALWARE_DETECTED', 'A malware is detect in website link.'), ('WEBSITE_CONTENT_DETECTED', 'Website content is changed.'), ('SERVER_STATUS', 'server status'), ('SERVICE_STATUS', 'services status')], null=True),
        ),
        migrations.AlterField(
            model_name='websitesecurityalertmodel',
            name='solution',
            field=models.TextField(blank=True, choices=[('NEW_DEVICE', 'Please check list devices connected in your network.'), ('DEVICE_TURN_OFF', 'Please check your network connection with your device.'), ('DEVICE_CHANGE_IP', "Please check network connection if you don't setting dhcp."), ('CANNOT_CONNECT_TO_TARGET', 'Please check your network connection of your device and your targets.'), ('NEW_SERVICE', "Please check the service of your device is you don't open port."), ('SERVICE_CHANGED', "Please check the service of your device is you don't do this."), ('SERVICE_CLOSED', "Please check the service of your device is you don't close port."), ('SERVICE_VERSION_TOO_OLD', 'Please update the last version of software.'), ('NEW_VULNERABILITY', ''), ('VULNERABILITY_IS_NOT_FIX', ''), ('NEW_SESSION', ''), ('NEW_PENETRATION', ''), ('BKACLIST_DETECTED', 'Please check mail or website content or contact domain blacklists checker with to unblock.'), ('MALWARE_DETECTED', 'Please check website content source security.'), ('WEBSITE_CONTENT_DETECTED', ''), ('SERVER_STATUS', 'server status'), ('SERVICE_STATUS', 'services status')], null=True),
        ),
    ]
