# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_auto_20180604_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoststatisticsmodel',
            name='ip_addr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
