# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficesStatistics',
            fields=[
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to='units.OfficesModel')),
                ('last_update', models.IntegerField(default=time.time, editable=False)),
                ('targets_count', models.IntegerField(default=0)),
                ('hosts_count', models.IntegerField(default=0)),
                ('services_count', models.IntegerField(default=0)),
                ('vulns_count', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('abnormal_alert_count', models.IntegerField(default=0)),
                ('security_alert_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'offices_statistic',
            },
        ),
        migrations.CreateModel(
            name='UnitsStatistics',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to='units.UnitsModel')),
                ('last_update', models.IntegerField(default=time.time, editable=False)),
                ('targets_count', models.IntegerField(default=0)),
                ('hosts_count', models.IntegerField(default=0)),
                ('services_count', models.IntegerField(default=0)),
                ('vulns_count', models.IntegerField(default=0)),
                ('sessions_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('abnormal_alert_count', models.IntegerField(default=0)),
                ('security_alert_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'units_statistic',
            },
        ),
        migrations.AddField(
            model_name='officesmodel',
            name='severity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unitsmodel',
            name='severity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='units.UnitsModel'),
        ),
        migrations.AlterField(
            model_name='unitsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to=settings.AUTH_USER_MODEL),
        ),
    ]
