# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20180529_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officesstatistics',
            old_name='sessions_count',
            new_name='db_attack_count',
        ),
        migrations.RenameField(
            model_name='unitsstatistics',
            old_name='sessions_count',
            new_name='db_attack_count',
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='domain_blacklist_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='malware_path_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='paths_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='phishing_domain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='server_configs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='subdomains_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='website_content_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officesstatistics',
            name='website_down_status_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='domain_blacklist_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='malware_path_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='paths_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='phishing_domain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='server_configs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='subdomains_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='website_content_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitsstatistics',
            name='website_down_status_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterUniqueTogether(
            name='officesmodel',
            unique_together=set([('unit', 'name')]),
        ),
    ]
