# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginsGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'plugins_group',
            },
        ),
        migrations.CreateModel(
            name='PluginsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(auto_created=1509915258)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('fname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'plugins',
            },
        ),
        migrations.CreateModel(
            name='PluginsLicenseModel',
            fields=[
                ('plugin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='plugins_license', serialize=False, to='plugins.PluginsModel')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('license', models.CharField(max_length=45)),
                ('expires', models.IntegerField()),
                ('activated', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plugins_license',
            },
        ),
        migrations.AddField(
            model_name='pluginsmodel',
            name='plugin_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin', to='plugins.PluginsGroupModel'),
        ),
    ]
