# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_auto_20171106_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsgroupmodel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pluginsmodel',
            name='created_at',
            field=models.IntegerField(auto_created=1510006480),
        ),
    ]
