# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_auto_20171107_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginsmodel',
            name='created_at',
            field=models.IntegerField(auto_created=1510010173),
        ),
    ]
