# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-22 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Error')], default=0)),
                ('is_watched', models.BooleanField(default=False)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems_log', to='sadmin.PluginsModel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems_log', to='targets.TargetsModel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems_log', to='targets.TasksModel')),
            ],
            options={
                'db_table': 'systems_log',
            },
        ),
        migrations.CreateModel(
            name='SystemsAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Dangerous')], default=0)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.IntegerField(editable=False)),
                ('is_watched', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems_alert', to='targets.TargetsModel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems_alert', to='targets.TasksModel')),
            ],
            options={
                'db_table': 'systems_alert',
            },
        ),
        migrations.CreateModel(
            name='SystemsEmailNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=45)),
                ('port', models.CharField(blank=True, max_length=45, null=True)),
                ('from_address', models.CharField(blank=True, max_length=45, null=True)),
                ('security', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('enable', models.BooleanField(default=False)),
                ('test_connection', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'systems_email_notify',
            },
        ),
        migrations.CreateModel(
            name='SystemsLicense',
            fields=[
                ('license_key', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('product_code', models.CharField(blank=True, max_length=45, null=True)),
                ('max_scans', models.IntegerField(default=2)),
                ('company', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('maintenance_expires', models.CharField(blank=True, max_length=45, null=True)),
                ('build_number', models.CharField(max_length=225)),
                ('plugins', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None)),
            ],
            options={
                'db_table': 'systems_license',
            },
        ),
        migrations.CreateModel(
            name='SystemsNetworkConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static', models.BooleanField()),
                ('type', models.IntegerField(choices=[(0, 'USER INTERFACE'), (1, 'MANAGERMENT INTERFACE')], default=0)),
                ('interface', models.CharField(max_length=225, unique=True)),
                ('ip_addr', models.CharField(blank=True, max_length=45, null=True)),
                ('netmask', models.CharField(blank=True, max_length=45, null=True)),
                ('gateway', models.CharField(blank=True, max_length=45, null=True)),
                ('mac_addr', models.CharField(blank=True, max_length=20, null=True)),
                ('test_connection', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'systems_network_config',
            },
        ),
        migrations.CreateModel(
            name='SystemsProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('protocol', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('test_connection', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'systems_proxy',
            },
        ),
        migrations.CreateModel(
            name='SystemStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statistic', models.DateField(auto_now_add=True)),
                ('hosts_count', models.IntegerField(default=0)),
                ('services_count', models.IntegerField(default=0)),
                ('subdomains_count', models.IntegerField(default=0)),
                ('paths_count', models.IntegerField(default=0)),
                ('server_configs_count', models.IntegerField(default=0)),
                ('db_attack_count', models.IntegerField(default=0)),
                ('vulns_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'systems_statistics',
            },
        ),
        migrations.CreateModel(
            name='SystemVPNModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('time_interval', models.IntegerField(blank=True, default=120)),
            ],
        ),
    ]
