# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatistics',
            name='blacklist_detect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='malware_path_count',
            field=models.IntegerField(default=0),
        ),
    ]
