# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20180529_1301'),
        ('systems', '0002_auto_20180402_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsalert',
            name='content',
        ),
        migrations.RemoveField(
            model_name='systemsalert',
            name='target',
        ),
        migrations.RemoveField(
            model_name='systemsalert',
            name='task',
        ),
        migrations.RemoveField(
            model_name='systemsalert',
            name='type',
        ),
        migrations.AddField(
            model_name='systemsalert',
            name='contents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='agents.WebsiteSecurityAlertModel'),
        ),
        migrations.AddField(
            model_name='systemsnetworkconfig',
            name='dns_server',
            field=models.CharField(blank=True, default='8.8.8.8', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='abnormal_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='security_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='severity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems_log', to='sadmin.PluginsModel'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems_log', to='targets.TargetsModel'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems_log', to='targets.TasksModel'),
        ),
        migrations.AlterField(
            model_name='systemsalert',
            name='created_at',
            field=models.IntegerField(default=time.time, editable=False),
        ),
        migrations.AlterModelTable(
            name='systemvpnmodel',
            table='systems_vpn',
        ),
    ]
