# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20180529_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemstatistics',
            old_name='blacklist_detect_count',
            new_name='domain_blacklist_alert_count',
        ),
        migrations.RemoveField(
            model_name='systemstatistics',
            name='date_statistic',
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='phishing_domain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='website_content_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstatistics',
            name='website_down_status_count',
            field=models.IntegerField(default=0),
        ),
    ]
