# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 06:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsmodel',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='reportsmodel',
            name='filter',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reportsmodel',
            name='host',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsmodel',
            name='office',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsmodel',
            name='severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='reportsmodel',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsmodel',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportstemplatesmodel',
            name='filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='reportstemplatesmodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNIT'), (1, 'OFFICE'), (2, 'TARGET'), (3, 'TASK'), (4, 'HOST'), (5, 'EVENT')], default=0),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='task',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sadmin.ReportsTemplatesModel'),
        ),
        migrations.AlterField(
            model_name='reportstemplatesmodel',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterUniqueTogether(
            name='reportsmodel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='reportstemplatesmodel',
            name='template_filename',
        ),
        migrations.AlterUniqueTogether(
            name='reportstemplatesmodel',
            unique_together=set([('type', 'name')]),
        ),
    ]
