# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 09:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0002_auto_20180529_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsmodel',
            name='file_type',
            field=models.CharField(blank=True, default='docx', max_length=30),
        ),
        migrations.AddField(
            model_name='reportstemplatesmodel',
            name='file_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={1: 'docx'}),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='events',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='host',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='office',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='task',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
