# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 20:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0003_auto_20180603_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsmodel',
            name='filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=150), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='reportstemplatesmodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNIT'), (1, 'OFFICE'), (2, 'TARGET'), (3, 'TASK'), (4, 'HOST'), (5, 'EVENT'), (6, 'SYSTEM')], default=0),
        ),
    ]
