# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-05 03:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0004_auto_20180605_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsmodel',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportsmodel',
            name='filter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None),
        ),
    ]
