# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_taskstatisticsmodel_malware_path_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatisticsmodel',
            name='domain_blacklist_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatisticsmodel',
            name='phishing_domain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatisticsmodel',
            name='security_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatisticsmodel',
            name='website_content_alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='targetsmodel',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='units.OfficesModel'),
        ),
        migrations.AlterField(
            model_name='targetsmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='targets.TargetsModel'),
        ),
    ]
