# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20180529_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatisticsmodel',
            name='abnormal_alert_count',
            field=models.IntegerField(default=0),
        ),
    ]
