# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_taskstatisticsmodel_abnormal_alert_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatisticsmodel',
            name='website_down_status_count',
            field=models.IntegerField(default=0),
        ),
    ]
